config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  mount Facebook::Messenger::Server, at: 'bot'

  root to: 'pages#home'
  get '/dashboard', to: 'dashboards#index'

  namespace :dashboard do
    resources :ongoing, controller: "ongoings", only: [:index]
    resources :templates, controller: "questionaires" do
      resources :questions, only: [:create, :destroy]
    end
    resources :treatments, controller: "treatment_processes" do 
      resources :evaluations, only: [:show]
      resources :checkpoints, only: [:destroy] do
        member do 
          delete :destroy_all_checkpoints
        end
      end
    end
    resources :users, only: [:show, :index]
  end


  get '/facebook_account_link', to: 'synchronisations#facebook_account_link'
  get '/facebook_account_confirmation', to: 'synchronisations#facebook_account_confirmation'
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionaire

  has_many :question_options, inverse_of: :question, dependent: :destroy
  accepts_nested_attributes_for :question_options, reject_if: :all_blank, allow_destroy: true

  validates :category, inclusion: { in: ["Yes/No", "Multiple choice", "Open", "Scale"] }
  validates :content, presence: true
end

app/controllers/dashboard/checkpoints_controller.rb
class Dashboard::CheckpointsController < ApplicationController
  before_action :set_treatment, only: [:destroy_all_checkpoints]
  before_action :set_checkpoint, only: [:destroy]

  def destroy
    @checkpoint.destroy
    redirect_to dashboard_treatments_path
    flash[:notice] = "Succsfully removed checkpoint for #{@checkpoint.scheduled_day}"
  end

  def destroy_all_checkpoints
    @treatment.checkpoints.destroy_all
    redirect_to dashboard_treatments_path
    flash[:notice] = "Succsfully removed all checkpoints for #{@treatment.client.full_name}"
  end

  private

  def set_treatment
    @treatment = TreatmentProcess.find(params[:treatment_id])
  end

  def set_checkpoint
    @checkpoint = Checkpoint.find(params[:id])
  end
end

app/controllers/dashboard/evaluations_controller.rb
class Dashboard::EvaluationsController < ApplicationController
  def show
    @evaluation = Evaluation.find(params[:id])
    unless @evaluation.viewed == true
      @evaluation.update(viewed: true)
    end
  end
end

app/controllers/dashboard/ongoings_controller.rb
class Dashboard::OngoingsController < ApplicationController
  def index
  end
end

app/controllers/dashboard/questionaires_controller.rb
class Dashboard::QuestionairesController < ApplicationController
  before_action :set_questionaire, only: [:show, :edit, :update, :destroy]

  def index
    @questionaires = Questionaire.all
  end

  def show
    @question = Question.new
    @question.question_options.build
    check_evaluations_size
  end

  def new
    @questionaire = Questionaire.new
  end

  def create
    @questionaire = Questionaire.new(questionaire_params)

    if @questionaire.save
      redirect_to dashboard_template_path(@questionaire)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @questionaire.destroy
    redirect_to dashboard_templates_path
  end

  private

  def check_evaluations_size
    @evaluations = Evaluation.joins(:treatment_process).where('questionaire_id = ?', @questionaire.id)
    if @evaluations.size == 0
      @text_evaluations = "no evaluations for this questionaire"
    elsif @evaluations.size == 1
      @text_evaluations = "1 evaluation for this questionaire"
    else
      @text_evaluations = "#{@evaluations.size} evaluations for this questionaire"
    end
  end

  def set_questionaire
    @questionaire = Questionaire.find(params[:id])
  end

  def questionaire_params
    params.require(:questionaire).permit(:title, :instruction)
  end
end

app/controllers/dashboard/questions_controller.rb
class Dashboard::QuestionsController < ApplicationController
  before_action :set_questionaire, only: [:create, :destroy]

  def create
    @question = Question.new(question_params)
    @question.questionaire = @questionaire
    if @question.save
      respond_to do |format|
        format.html { redirect_to dashboard_template_path(@questionaire) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
       respond_to do |format|
        format.html { render 'dashboard/templates/show' }       # not sure about this
        format.js  # <-- idem
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to dashboard_template_path(@questionaire)
  end

  private

  def set_questionaire
    @questionaire = Questionaire.find(params[:template_id])
  end

  def question_params
    params.require(:question).permit(:category, :content, question_options_attributes: [:id, :content, :_destroy])
  end
end

app/controllers/dashboard/treatment_processes_controller.rb
class Dashboard::TreatmentProcessesController < ApplicationController
  before_action :set_treatment_process, only: [:show, :edit, :update, :destroy]
  def index
    @treatments = TreatmentProcess.where(creator_id: current_user.id).group_by(&:status).sort_by { |key, value| key }.reverse
  end

  def show
    @message = TreatmentStatusService.new(treatment: @treatment).call
  end

  def new
    @treatment = TreatmentProcess.new
    @users = User.where.not(facebook_id: nil).order(:last_name)
    @questionaires = Questionaire.all
    @frequency_options = %w(daily weekly)
    @duration_options = ["one_week", "two_weeks", "one_month", "three_months"]
  end

  def create
    @treatment = TreatmentProcess.new(treatment_process_params)
    if @treatment.save
      CheckpointCreationService.new(treatment: @treatment).call
      redirect_to  dashboard_treatment_path(@treatment)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_treatment_process
    @treatment = TreatmentProcess.find(params[:id])
  end

  def treatment_process_params
    params.require(:treatment_process).permit(:client_id, :creator_id, :frequency, :duration, :start_date, :questionaire_id)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  def index
    @user = User.where(admin: false)
  end

  def show
    @treatment_process = TreatmentProcess.new
    @questionaires = Questionaire.all
    @user = User.find(params[:id])
  end

  def destroy
  end

  private

  def set_user
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @evaluations = Evaluation.joins(:treatment_process).where(treatment_processes: { creator_id: current_user.id }).where(viewed: false).limit(3)
    @running_treatments_amount = TreatmentProcess.where(creator: current_user, status: "Ongoing").count
  end
end

app/views/dashboard/questions/_form.html.erb
<div class="questions-form">
  <%= simple_form_for([ questionaire, question ], remote: true, html: { id: "question-form-dropdown" }, url: dashboard_template_questions_path(questionaire)) do |f| %>
  <h4>Add question</h4>
  <%= f.input :category, collection: ["Yes/No", "Multiple choice", "Open", "Scale"], input_html: {id: "category-question"} %>
  <%= f.input :content, placeholder: "Question" %>

  <div id="multiple-choice" class="hidden">
    <h5>Multiple choice options</h5>

    <div id="question-options">
      <%= f.simple_fields_for :question_options do |question_option| %>
      <%= render partial: 'question_option_fields', locals: { f: question_option } %>
      <% end %>
      <div class="links">
        <%= link_to_add_association 'add this option', f, :question_options, class: "btn teal" %>
      </div>
    </div>
  </div>
  <%= f.button :submit, id: "select-action"%>
  <% end %>
</div>

app/views/dashboard/questions/_question_option_fields.html.erb
<%= f.input :content %>
<%= link_to_remove_association "remove question options", f %>

app/views/dashboard/questions/_show.html.erb
<div class="collection-item">
  <div class="flex-question">
  <p><%= question.content %>
      <span><%= link_to dashboard_template_question_path(@questionaire, question), class: "btn-garage-remove", method: :delete do %>
        <i class="fa fa-window-close-o fa-lg" aria-hidden="true"></i>
        <% end %>
      </span>
    </p>
    <div class="question-category">
    <%= question.category %>
    </div>
  </div>
  <div class="question-options-container">
    <% if question.question_options.any? %>
    <ul>
      <% question.question_options.each do |question_option| %>
      <li>
        <%= question_option.content %>
      </li>
      <% end %>
      <% end %>
    </ul>
  </div>

</div>

app/views/dashboard/questions/create.js.erb
<% if @question.errors.any? %>
  // Render new review form with errors
  $('#new_question').html("<%= j render 'dashboard/questions/form', questionaire: @questionaire, question: @question %>");
<% else %>
  // Create a paragraph for the new review. But hide it.
  var new_question = $("<%= j render 'dashboard/questions/show', question: @question %>").hide();
  // Add it to the DOM, at the end of the existing reviews. It's still hidden.
  $('#questions .collection.with-header').append(new_question);
  // Show the new review with an animation!
  new_question.slideDown();
  // Reset the form
  $('#no-questions').text('Questions');
  $('.question_category input').val("");
  $('#question-form-dropdown .question_content textarea').val("");
  $('#new_question').html("<%= j render 'dashboard/questions/form', questionaire: @questionaire, question: Question.new %>");
<% end %>