config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  mount Facebook::Messenger::Server, at: 'bot'

  root to: 'pages#home'
  get '/dashboard', to: 'dashboards#index'

  namespace :dashboard do
    resources :ongoing, controller: "ongoings", only: [:index]
    resources :templates, controller: "questionaires" do
      resources :questions, only: [:create, :destroy]
    end
    resources :treatments, controller: "treatment_processes" do 
      resources :evaluations, only: [:show]
      resources :checkpoints, only: [:destroy] do
        member do 
          delete :destroy_all_checkpoints
        end
      end
    end
    resources :users, only: [:show, :index]
  end


  get '/facebook_account_link', to: 'synchronisations#facebook_account_link'
  get '/facebook_account_confirmation', to: 'synchronisations#facebook_account_confirmation'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question
  belongs_to :evaluation
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/checkpoint.rb
class Checkpoint < ApplicationRecord
  belongs_to :treatment_process
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :user
  belongs_to :treatment_process
  has_many :answers, dependent: :destroy
  has_many :questions, through: :questionaire
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
end

app/models/pending_evaluation.rb
class PendingEvaluation < ApplicationRecord
  belongs_to :treatment_process
  belongs_to :user

  def self.generate_and_cleanup
    Checkpoint.where(scheduled_day: Date.today).each do |checkpoint|
      PendingEvaluation.where(treatment_process: checkpoint.treatment_process).destroy_all

      PendingEvaluation.create(
        treatment_process: checkpoint.treatment_process, 
        user: checkpoint.treatment_process.client
        )
    end
  end

  def self.initiate_conversation
    PendingEvaluation.all.each do |pending_evaluation|
      InitiateConversationService.new(pending_evaluation: pending_evaluation).call
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :questionaire

  has_many :question_options, inverse_of: :question, dependent: :destroy
  accepts_nested_attributes_for :question_options, reject_if: :all_blank, allow_destroy: true

  validates :category, inclusion: { in: ["Yes/No", "Multiple choice", "Open", "Scale"] }
  validates :content, presence: true
end

app/models/question_option.rb
class QuestionOption < ApplicationRecord
  belongs_to :question
end

app/models/questionaire.rb
class Questionaire < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :evaluations
  has_many :treatment_processes

  validates :title, presence: true
  validates :instruction, presence: true
end

app/models/treatment_process.rb
class TreatmentProcess < ApplicationRecord
  belongs_to :questionaire
  belongs_to :client, class_name: "User"
  belongs_to :creator, class_name: "User"
  has_many :evaluations
  after_create :set_status
  has_many :checkpoints

  def end_date
    TreatmentStatusService.new(treatment: self).end_date
  end

  private

  def set_status
    TreatmentStatusService.new(treatment: self).call
  end
end

app/models/user.rb
Rails.application.config.active_record.belongs_to_required_by_default = false

class User < ApplicationRecord
  devise :omniauthable, omniauth_providers: [:facebook]

  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable

  belongs_to :coach, class_name: "User"
  has_many :treatment_processes
  has_many :questionaires, through: :treatment_processes
  has_many :evaluations
  has_many :pending_evaluations


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    # Monkey patch
    unless auth.credentials.expires_at.nil?
      user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    end
    user_params = user_params.to_h

    user = User.where(provider: auth.provider, uid: auth.uid).first
    user ||= User.where(email: auth.info.email).first # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

  def full_name
    "#{self.first_name} #{self.last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :facebook_id])
  end

  def after_sign_in_path_for(resource)
     dashboard_path
  end
end

app/controllers/dashboard/ongoings_controller.rb
class Dashboard::OngoingsController < ApplicationController
  def index
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  def index
    @user = User.where(admin: false)
  end

  def show
    @treatment_process = TreatmentProcess.new
    @questionaires = Questionaire.all
    @user = User.find(params[:id])
  end

  def destroy
  end

  private

  def set_user
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @evaluations = Evaluation.joins(:treatment_process).where(treatment_processes: { creator_id: current_user.id }).where(viewed: false).limit(3)
    @running_treatments_amount = TreatmentProcess.where(creator: current_user, status: "Ongoing").count
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  def home
  end
end

app/controllers/synchronisations_controller.rb
class SynchronisationsController < ApplicationController
  def facebook_account_link
    current_user.facebook_id = params[:fb_messenger_id]
    if current_user.save
      redirect_to facebook_account_confirmation_path
    else
      flash[:error] = "Synchronisation failed"
    end
  end

  def facebook_account_confirmation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/garage_bot_helper.rb
module GarageBotHelper
  def bot_user_exists?(facebook_id)
    if User.find_by_facebook_id(facebook_id).nil?
      return false 
    else 
      return true
    end
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/cards/_evaluation_card.html.erb
<%= link_to dashboard_treatment_evaluation_path(treatment, evaluation), class: "collection-item" do  %>
<p>
  Evaluation conducted on: <strong><%= evaluation.created_at.strftime('%A') %> <%= evaluation.created_at %></strong>
</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Garage Bot</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  </head>
  <body class="<%= params[:controller] %>-<%= params[:action] %>">
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-page">
  <div class="container">
    <div class="row">
      <div class="col s12">
        <div class="home-title">
          <h2>Garagebot</h2>
        </div>
        <div class="home-paragraph-title">
          <p>A project built by Unless, commissioned by Garage2020</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col s6">
        <div class="giphy" style="background-image:url('https://media.giphy.com/media/JSRZTSrvQSGkg/giphy.gif');"></div>
      </div>
      <div class="col s6">
        <h5>Hello 🤖</h5>
        <div class="p-expl-text">
          <p> 
            A bot by Garage2020 & Unless to help healthcare workers conduct questionaires.
          </p>
          <p>
          The Garagebot was built to help youth workers in asking frequent questionaires in a more fun and constructive way. By becoming part of this platform, you can start creating a template for questionaires you wish the bot to conduct on a regular basis. Instead of using plain old paper, this platform will allow you to send a bot to Facebook Messenger with the purpose of gathering information from your clients. By using the chat tool, we believe that clients, will enjoy the filling out of these questionaires more, so overall delivering a better experience for them.
          </p>
        </div>
        <div class="team-finish">
          <p>Best,</p>
          <p>The Team</p>
        </div>
      </div>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
 <footer class="page-footer teal footer-custom">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Garagebot</h5>
        <p class="grey-text text-lighten-4">
          A bot by Garage2020 & Unless to help healthcare workers conduct questionaires.
        </p>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
      © 2017 Garage2020 & Unless
      <a class="grey-text text-lighten-4 right" href="http://unless.io">Made by Unless.io</a>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
 <nav>
  <div class="nav-wrapper teal">
    <div class="garage-nav">
      <%= link_to "Garagebot", root_path, class: "garage-logo" %>

      <% if user_signed_in?  %>

      <!-- Dropdown Trigger -->
      <% if current_user.facebook_picture_url.nil? %>
      <%= link_to "", "#", id: "navbar-menu", class: "navbar-dropdown", style: "background-image: url(#{image_path("placeholder_bunny.jpeg")})", "data-activates": "dropdown1" %>
      <% else %>
      <%= link_to "", "#", id: "navbar-menu", class: "navbar-dropdown", style: "background-image: url(#{current_user.facebook_picture_url})", "data-activates": "dropdown1" %>
      <% end %>

      <!-- Dropdown Structure -->
      <ul id='dropdown1' class='dropdown-content'>
        <li>
          <%= link_to dashboard_path do %>
          <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
          <% end %>
        </li>
        <li>
          <%= link_to root_path do %>
          <i class="fa fa-home"></i>  <%= t(".profile", default: "Home") %>
          <% end %>
        </li>
        <li class="divider"></li>
        <li>
          <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
          <% end %>
        </li>
      </ul>

      <% else %>

      <%= link_to user_facebook_omniauth_authorize_path, class: "navbar-item navbar-link" do %>
      <i class="fa fa-<%= OmniAuth::Utils.camelize(:facebook).downcase %>"></i>
      Sign in with <%= OmniAuth::Utils.camelize(:facebook) %>
      <% end %>

      <!-- Login text link -->
      <!-- DISABLED -->
      <% link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-item navbar-link" %>
      <!-- END DISABLED -->
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
  <div class="links">

    <!-- LINK TO DASHBOARD START -->
    <div class="link">
      <%= link_to dashboard_path, class: "general-link" do %>
      Dashboard
        <%= render partial: "shared/sidebar_underline", locals: { controller: "dashboards" } %>
      <% end %>
    </div>
    <!-- LINK TO DASHBOARD END -->

    <div class="divider"></div>

    <!-- LINK TO TEMPLATES START -->
    <div class="link">
      <%= link_to dashboard_templates_path, class: "general-link" do %>
        Templates
         <%= render partial: "shared/sidebar_underline", locals: { controller: "dashboard/questionaires" } %>
      <% end %>
      <div class="add">
        <%= link_to new_dashboard_template_path do %>
          <i class="fa fa-plus"></i>
        <% end %>
      </div>
    </div>
    <!-- LINK TO TEMPLATES END -->

    <div class="divider"></div>

    <!-- LINK TO TREATMENS START -->
    <div class="link">
      <%= link_to dashboard_treatments_path, class: "general-link" do %>
        Treatments
        <%= render partial: "shared/sidebar_underline", locals: { controller: "dashboard/treatment_processes" } %>
      <% end %>
      <div class="add">
        <%= link_to new_dashboard_treatment_path do %>
          <i class="fa fa-plus"></i>
        <% end %>
      </div>
    </div>
    <!-- LINK TO TREATMENTS END -->
  </div>
</div>

app/views/shared/_sidebar_underline.html.erb
  <% if params[:controller] == controller %>
    <div class="underline active"></div>
  <% else %>
    <div class="underline"></div>
  <% end %>