config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks', registrations: 'users/registrations' }

  mount Facebook::Messenger::Server, at: 'bot'

  root to: 'pages#home'
  get '/dashboard', to: 'dashboards#index'

  namespace :dashboard do
    resources :ongoing, controller: "ongoings", only: [:index]
    resources :templates, controller: "questionaires" do
      resources :questions, only: [:create, :destroy]
    end
    resources :treatments, controller: "treatment_processes" do 
      resources :evaluations, only: [:show]
      resources :checkpoints, only: [:destroy] do
        member do 
          delete :destroy_all_checkpoints
        end
      end
    end
    resources :users, only: [:show, :index]
  end


  get '/facebook_account_link', to: 'synchronisations#facebook_account_link'
  get '/facebook_account_confirmation', to: 'synchronisations#facebook_account_confirmation'
end

app/controllers/dashboard/checkpoints_controller.rb
class Dashboard::CheckpointsController < ApplicationController
  before_action :set_treatment, only: [:destroy_all_checkpoints]
  before_action :set_checkpoint, only: [:destroy]

  def destroy
    @checkpoint.destroy
    redirect_to dashboard_treatments_path
    flash[:notice] = "Succsfully removed checkpoint for #{@checkpoint.scheduled_day}"
  end

  def destroy_all_checkpoints
    @treatment.checkpoints.destroy_all
    redirect_to dashboard_treatments_path
    flash[:notice] = "Succsfully removed all checkpoints for #{@treatment.client.full_name}"
  end

  private

  def set_treatment
    @treatment = TreatmentProcess.find(params[:treatment_id])
  end

  def set_checkpoint
    @checkpoint = Checkpoint.find(params[:id])
  end
end

app/controllers/dashboard/evaluations_controller.rb
class Dashboard::EvaluationsController < ApplicationController
  def show
    @evaluation = Evaluation.find(params[:id])
    unless @evaluation.viewed == true
      @evaluation.update(viewed: true)
    end
  end
end

app/controllers/dashboard/ongoings_controller.rb
class Dashboard::OngoingsController < ApplicationController
  def index
  end
end

app/controllers/dashboard/questionaires_controller.rb
class Dashboard::QuestionairesController < ApplicationController
  before_action :set_questionaire, only: [:show, :edit, :update, :destroy]

  def index
    @questionaires = Questionaire.all
  end

  def show
    @question = Question.new
    @question.question_options.build
    check_evaluations_size
  end

  def new
    @questionaire = Questionaire.new
  end

  def create
    @questionaire = Questionaire.new(questionaire_params)

    if @questionaire.save
      redirect_to dashboard_template_path(@questionaire)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
  end

  def destroy
    @questionaire.destroy
    redirect_to dashboard_templates_path
  end

  private

  def check_evaluations_size
    @evaluations = Evaluation.joins(:treatment_process).where('questionaire_id = ?', @questionaire.id)
    if @evaluations.size == 0
      @text_evaluations = "no evaluations for this questionaire"
    elsif @evaluations.size == 1
      @text_evaluations = "1 evaluation for this questionaire"
    else
      @text_evaluations = "#{@evaluations.size} evaluations for this questionaire"
    end
  end

  def set_questionaire
    @questionaire = Questionaire.find(params[:id])
  end

  def questionaire_params
    params.require(:questionaire).permit(:title, :instruction)
  end
end

app/controllers/dashboard/questions_controller.rb
class Dashboard::QuestionsController < ApplicationController
  before_action :set_questionaire, only: [:create, :destroy]

  def create
    @question = Question.new(question_params)
    @question.questionaire = @questionaire
    if @question.save
      respond_to do |format|
        format.html { redirect_to dashboard_template_path(@questionaire) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
       respond_to do |format|
        format.html { render 'dashboard/templates/show' }       # not sure about this
        format.js  # <-- idem
      end
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to dashboard_template_path(@questionaire)
  end

  private

  def set_questionaire
    @questionaire = Questionaire.find(params[:template_id])
  end

  def question_params
    params.require(:question).permit(:category, :content, question_options_attributes: [:id, :content, :_destroy])
  end
end

app/controllers/dashboard/treatment_processes_controller.rb
class Dashboard::TreatmentProcessesController < ApplicationController
  before_action :set_treatment_process, only: [:show, :edit, :update, :destroy]
  def index
    @treatments = TreatmentProcess.where(creator_id: current_user.id).group_by(&:status).sort_by { |key, value| key }.reverse
  end

  def show
    @message = TreatmentStatusService.new(treatment: @treatment).call
  end

  def new
    @treatment = TreatmentProcess.new
    @users = User.where.not(facebook_id: nil).order(:last_name)
    @questionaires = Questionaire.all
    @frequency_options = %w(daily weekly)
    @duration_options = ["one_week", "two_weeks", "one_month", "three_months"]
  end

  def create
    @treatment = TreatmentProcess.new(treatment_process_params)
    if @treatment.save
      CheckpointCreationService.new(treatment: @treatment).call
      redirect_to  dashboard_treatment_path(@treatment)
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def set_treatment_process
    @treatment = TreatmentProcess.find(params[:id])
  end

  def treatment_process_params
    params.require(:treatment_process).permit(:client_id, :creator_id, :frequency, :duration, :start_date, :questionaire_id)
  end
end

app/controllers/dashboard/users_controller.rb
class Dashboard::UsersController < ApplicationController
  def index
    @user = User.where(admin: false)
  end

  def show
    @treatment_process = TreatmentProcess.new
    @questionaires = Questionaire.all
    @user = User.find(params[:id])
  end

  def destroy
  end

  private

  def set_user
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    @evaluations = Evaluation.joins(:treatment_process).where(treatment_processes: { creator_id: current_user.id }).where(viewed: false).limit(3)
    @running_treatments_amount = TreatmentProcess.where(creator: current_user, status: "Ongoing").count
  end
end

app/views/dashboard/treatment_processes/_radio_buttons_treatment.html.erb
<div class="form-group radio_buttons optional treatment_process_<%= type %>">
  <label class="control-label radio_buttons optional">
    <%= type %>
  </label>
  <input type="hidden" name="treatment_process[<%= type %>]" value="">

  <% options.each do |option| %>
  <p>
    <input name="treatment_process[<%= type %>]" type="radio" id="<%= type %>_<%= option %>" value="<%= option.gsub(/_/, " ") %>"/>
    <label for="<%= type %>_<%= option %>">
      <%= option.gsub(/_/, " ").capitalize %>
    </label>
  </p>
  <% end %>
</div>

app/views/dashboard/treatment_processes/index.html.erb
<div class="container-custom">
  <div class="row">
    <div class="col s4">
      <%= render partial: "shared/sidebar" %>
    </div>
    <div class="col s8">
      <h4>
        All treatments
      </h4>
      <% @treatments.each do |status, treatments| %>
      <div class="row">
        <h5>
          <%= status %>
        </h5>
        <% treatments.each do |treatment| %>          
        <div class="col s4">
          <div class="card  teal lighten-3">
            <div class="card-content white-text">
              <%= link_to dashboard_treatment_path(treatment), class: "deep-orange-text" do %>
              <span class="card-title">
                <%= treatment.client.full_name %>
              </span>
              <% end %>
              <strong>
                <%= treatment.questionaire.title %>
              </strong>
              <p>
                Started: <%= treatment.start_date.strftime("%d/%m/%Y") %>
              </p>
              <p>
                Ends: <%= treatment.end_date.strftime("%d/%m/%Y") %>
              </p>
            </div>
          </div>
        </div>
        <% end %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/treatment_processes/new.html.erb
<div class="container-custom">
  <div class="row">
    <div class="col s4">
      <%= render partial: "shared/sidebar" %>
    </div>
    <div class="col s8">
      <h3>
        Schedule a questionaire
      </h3>
      <%= simple_form_for @treatment, url: dashboard_treatments_path do |f| %>
        <%= f.input :creator_id, as: :hidden, input_html: { value: current_user.id } %>
        <%= f.input :client_id, collection: @users.map {|user| ["#{user.last_name}, #{user.first_name}", user.id]} %>
        <%= f.input :questionaire_id, collection: @questionaires.map {|questionaire| [questionaire.title, questionaire.id]} %>
        <%= render partial: "radio_buttons_treatment", locals: { f: f, options: @frequency_options, type: "frequency" } %>
        <%= render partial: "radio_buttons_treatment", locals: { f: f, options: @duration_options, type: "duration" } %>
        <%= f.input :start_date %>
        <%= f.submit class: "waves-effect waves-light btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/dashboard/treatment_processes/show.html.erb
<div class="container-custom">
  <div class="row">
    <div class="col s4">
      <%= render partial: "shared/sidebar" %>
    </div>
    <div class="col s8">
      <h4>
        <%= @treatment.questionaire.title %> process for <%= @treatment.client.full_name %>
      </h4>
      <%= @message %> - <%= @treatment.checkpoints.length %> interactions remaining

      <% if @treatment.evaluations.any? %>
      <ul class="collection">
        <% @treatment.evaluations.each do |evaluation| %>
        <%= link_to dashboard_treatment_evaluation_path(@treatment, evaluation), class: "collection-item" do  %>
        <p>
          Evaluation conducted on: <strong><%= evaluation.created_at.strftime('%A') %> <%= evaluation.created_at %></strong>
        </p>
        <% end %>
        <% end %>
      </ul>
      <% end %>
      <% if @treatment.checkpoints.any? %>
      <h4>
        Scheduled interactions
      </h4>
      <%= link_to destroy_all_checkpoints_dashboard_treatment_checkpoint_path(@treatment), method: :delete, data: {confirm: 'Are you sure?' } do %>
      <h6 class="black-text">
        Destroy all checkpoints
        <span class="red-text">
          <i class="fa fa-times">
          </i>
        </span>
      </h6>
      <% end %>
      <ul class="collection">
        <% @treatment.checkpoints.each do |checkpoint| %>
        <li class="collection-item">
          <div class="checkpoint-item">
            <%= checkpoint.scheduled_day %>
            <%= link_to dashboard_treatment_checkpoint_path(@treatment, checkpoint), class: "red-text", method: :delete do %>
            <i class="fa fa-times"></i>
            <% end %>
          </div>
        </li>
        <% end %>
      </ul>
      <% end %>
    </div>
  </div>
</div>